Vagrant.configure("2") do |config|
  # Usar provider Google Cloud
  config.vm.provider :google do |g|
    g.google_project_id = "SEU_PROJECT_ID_AQUI"
    g.google_json_key_location = "~/.gcp/vagrant-key.json"
    g.zone = "europe-west1-b"  # exemplo, muda conforme teu projeto
    g.machine_type = "e2-medium"
  end

  # Box do Google Cloud
  config.vm.box = "google/gce"

  # ---------------------------
  # Servidor OpenLDAP
  # ---------------------------
  config.vm.define "ldap_server" do |ldap|
    ldap.vm.provider :google do |g|
      g.name = "ldap-server"
      g.image_project_id = "ubuntu-os-cloud"
      g.image_family = "ubuntu-2004-lts"
    end

    ldap.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.inventory_path = "ansible/hosts.ini"
      ansible.limit = "ldap_server"
    end
  end

  # ---------------------------
  # Servidor NAS
  # ---------------------------
  config.vm.define "nas_server" do |nas|
    nas.vm.provider :google do |g|
      g.name = "nas-server"
      g.image_project_id = "debian-cloud"
      g.image_family = "debian-11"
    end

    nas.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.inventory_path = "ansible/hosts.ini"
      ansible.limit = "nas_server"
    end
  end

  # ---------------------------
  # Workstation Ubuntu
  # ---------------------------
  config.vm.define "ubuntu_workstation" do |ws|
    ws.vm.provider :google do |g|
      g.name = "ubuntu-ws"
      g.image_project_id = "ubuntu-os-cloud"
      g.image_family = "ubuntu-2004-lts"
    end

    ws.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.inventory_path = "ansible/hosts.ini"
      ansible.limit = "linux_clients"
    end
  end
end
