# Vagrantfile para VirtualBox (Arquitetura x86_64 - Host Intel/AMD)

Vagrant.configure("2") do |config|
  
  # Boxes comuns e estáveis para VirtualBox (x86_64)
  UBUNTU_BOX = "generic/ubuntu2004" 
  DEBIAN_BOX = "generic/debian11" 

  # Configuração padrão (para todas as VMs)
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end


  # 1. Servidor OpenLDAP
  config.vm.define "ldap_server" do |ldap|
    ldap.vm.box = UBUNTU_BOX
    ldap.vm.hostname = "ldap-server"
    ldap.vm.network "private_network", ip: "192.168.56.10"
  end

  # 2. Servidor NAS (NFS)
  config.vm.define "nas_server" do |nas|
    nas.vm.box = DEBIAN_BOX 
    nas.vm.hostname = "nas-server"
    nas.vm.network "private_network", ip: "192.168.56.20"
  end

  # 3. Workstation Ubuntu
  config.vm.define "ubuntu_workstation" do |ws|
    ws.vm.box = UBUNTU_BOX
    ws.vm.hostname = "ubuntu-ws"
    ws.vm.network "private_network", ip: "192.168.56.100"
  end
  
  # Provisionamento Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.inventory_path = "ansible/hosts.ini"
  end
end