---
- name: Instalar pacotes NFS
  apt:
    name:
      - nfs-kernel-server
    state: present
    update_cache: yes

- name: Criar diretório compartilhado
  file:
    path: /srv/nfs/shared
    state: directory
    owner: nobody
    group: nogroup
    mode: '0777'

- name: Configurar exportação NFS
  lineinfile:
    path: /etc/exports
    line: "/srv/nfs/shared *(rw,sync,no_root_squash,no_subtree_check)"
    create: yes

- name: Aplicar exportações NFS
  command: exportfs -ra

- name: Iniciar serviço NFS
  service:
    name: nfs-kernel-server
    state: started
    enabled: yes
