---
- name: Instalar pacotes OpenLDAP
  apt:
    name:
      - slapd
      - ldap-utils
    state: present
    update_cache: yes

- name: Garantir que o serviço LDAP está ativo
  service:
    name: slapd
    state: started
    enabled: yes
