# Vagrantfile (Usando a box ARM/VMware mais estável)

Vagrant.configure("2") do |config|
  
  # Box ARM64 conhecida por funcionar com VMware Fusion
  UBUNTU_ARM_BOX = "spox/ubuntu-arm" 
  DEBIAN_ARM_BOX = "generic/debian11" # Tentativa, pode precisar de correção

  # 1. Servidor OpenLDAP
  config.vm.define "ldap_server" do |ldap|
    ldap.vm.box = UBUNTU_ARM_BOX
    ldap.vm.hostname = "ldap-server"
    ldap.vm.network "private_network", ip: "192.168.56.10"
    
    ldap.vm.provider "vmware_desktop" do |vmware|
      vmware.vmx["memsize"] = "1024" # 1 GB de RAM
    end
  end

  # 2. Servidor NAS (NFS)
  config.vm.define "nas_server" do |nas|
    nas.vm.box = DEBIAN_ARM_BOX 
    nas.vm.hostname = "nas-server"
    nas.vm.network "private_network", ip: "192.168.56.20"
    
    nas.vm.provider "vmware_desktop" do |vmware|
      vmware.vmx["memsize"] = "2048" # 2 GB de RAM
    end
  end

  # 3. Workstation Ubuntu
  config.vm.define "ubuntu_workstation" do |ws|
    ws.vm.box = UBUNTU_ARM_BOX
    ws.vm.hostname = "ubuntu-ws"
    ws.vm.network "private_network", ip: "192.168.56.100"
    
    ws.vm.provider "vmware_desktop" do |vmware|
      vmware.vmx["memsize"] = "1024" # 1 GB de RAM
    end
  end
  
  # Configuração do Provisionamento Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.inventory_path = "ansible/hosts.ini"
  end
end