---
- name: Instalar pacotes cliente LDAP e NFS
  apt:
    name:
      - libnss-ldap
      - libpam-ldap
      - ldap-utils
      - nfs-common
    state: present
    update_cache: yes

- name: Criar ponto de montagem para NFS
  file:
    path: /mnt/shared
    state: directory

- name: Montar diretório NFS
  mount:
    path: /mnt/shared
    src: "{{ hostvars['nas-server']['ansible_host'] }}:/srv/nfs/shared"
    fstype: nfs
    opts: rw
    state: mounted
