- name: Adicionar o recurso de Cliente NFS (Necessário para montar o NAS)
  # O Windows não suporta NFS por padrão, precisa desse recurso (Feature).
  ansible.windows.win_feature:
    name: NFS-Client
    state: present
    include_management_tools: yes
  register: nfs_feature
  
- name: Reiniciar se o recurso NFS foi instalado
  ansible.windows.win_reboot:
  when: nfs_feature.reboot_required

- name: Adicionar entrada DNS para o servidor LDAP/NAS (opcional, mas recomendado)
  # Isso garante que a resolução de nomes funcione
  ansible.windows.win_hosts:
    name: ldap-server
    ip: 192.168.56.10
    state: present
    
- name: Configurar o cliente para usar o OpenLDAP (via Powershell)
  # Isso exige a execução de scripts complexos de Powershell para configurar o
  # LDAP/AD, pois não há um módulo Ansible simples para isso.
  ansible.windows.win_shell: |
    # (Inserir comandos Powershell para configurar o cliente LDAP/AD)
    # Geralmente envolve configuração de registro ou ferramentas CLI específicas
    Write-Host "Configuração LDAP no Windows é complexa e precisa de script específico."
  
- name: Mapear a unidade de rede NFS
  # O mapeamento NFS é feito via WinShell pois é um comando CLI no Windows
  ansible.windows.win_shell: |
    # mount -o anon nas-server:/srv/nfs/dados X:
    Write-Host "Tentando mapear NFS..."
    mount nas-server:/srv/nfs/dados Z:
  ignore_errors: yes # A montagem pode falhar se o recurso NFS ainda não estiver 100% pronto
