---
- name: Instalar pacote RSAT-LDAP (Windows)
  win_feature:
    name: RSAT-AD-PowerShell
    state: present

- name: Configurar cliente LDAP (exemplo)
  win_shell: |
    Write-Host "Configuração LDAP simulada no cliente Windows"
